"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = '''
$hostname$directory $git_branch $git_metrics $git_status $git_state
$character
'''

right_format = '$cmd_duration $time'

[character]
success_symbol = "[->](green)"
error_symbol = "[->](red)"
vimcmd_symbol = "[->](yellow)"

[cmd_duration]
min_time = 0
show_milliseconds = true
format = '[\($duration\)](blue)'

[time]
disabled = false
utc_time_offset = "-3"
time_format = "%T"
format = '[\[$time\]](blue)'

[hostname]
ssh_only = false
ssh_symbol = "[#](green)"
trim_at = "."
format = '[$ssh_symbol$hostname@](blue)'

[directory]
truncation_length = 4
truncate_to_repo = true
truncation_symbol = "…/"
format = '[$path](bold cyan)'

[git_branch]
always_show_remote = true
symbol = " "
format = '[($symbol$branch)](bold yellow)'

[git_status]
conflicted = " $count"
ahead = "壟$count"
behind = "鹿 $count"
diverged = " $count"
up_to_date = ""
untracked = " $count"
stashed = " $count"
modified = "罹$count"
staged = " $count"
renamed = " $count"
deleted = " $count"
format = '[\[$all_status$ahead_behind\]](bold red)'

[git_metrics]
disabled = false
format = '[+$added]($added_style) [-$deleted]($deleted_style)'

[git_state]
disabled = false
