xsetroot -solid "#2E3440"
if [[ -f ~/.Xresources ]]; then
  xrdb -I$HOME ~/.Xresources
fi

sxhkd -c $HOME/.config/sxhkd/custom &
sxhkd -c $HOME/.config/sxhkd/main &
autorandr --change &
setxkbmap -layout us -variant altgr-intl -option ctrl:nocaps
lxqt-policykit-agent &
dunst &
nm-applet &
blueman-applet &

i3

#qtile start
